from __future__ import annotations

from .models import BattleInput


EXAMPLE_BATTLE = {
    "meta": {
        "scenario_name": "SGS Afrika Korps - Calculator Example",
        "turn_number": 5,
        "date_label": "Week 5, 1941",
        "active_side": "Axis",
        "phase": "Battles",
        "seed": 1941,
    },
    "battle": {
        "region": "Sidi Barrani",
        "terrain": "Clear desert with road",
        "attacker_combat_modifier": 0,
        "defender_combat_modifier": 1,
        "attacker_morale_modifier": 0,
        "defender_morale_modifier": 0,
        "air_modifier": -1,
        "artillery_modifier": 0,
        "mine_modifier": 0,
        "recon_modifier": 0,
        "connection_defender_modifier": 1,
        "defender_entrenched": True,
        "recon_allowed": True,
        "pursuit_allowed": True,
        "breakthrough_allowed": True,
        "armor_superiority_allowed": True,
        "max_next_rounds": 3,
    },
    "attacker": {
        "name": "Axis",
        "leader": {"name": "Rommel", "combat": 3, "morale": 2},
        "scenario_morale_bonus": 0,
        "boosters": [
            {
                "name": "Forward HQ",
                "combat": 0,
                "attack": 1,
                "defense": 0,
                "morale": 1,
                "rounds": [],
                "tags": [],
            }
        ],
        "modifiers": [
            {
                "name": "Prepared assault",
                "combat": 0,
                "attack": 1,
                "defense": 0,
                "morale": 0,
                "rounds": ["main", "next"],
                "tags": [],
            }
        ],
        "retreat_policy": {"mode": "never", "prevent_pursuit": True},
        "units": [
            {
                "id": "it-ari-132",
                "name": "132 Ariete Tank Bde",
                "role": "combat",
                "domain": "land",
                "attack": 5,
                "defense": 4,
                "morale": 4,
                "strength": 4,
                "max_strength": 4,
                "rof": 1,
                "tags": ["armor", "pursuit", "breakthrough"],
                "loss_priority": "normal",
            },
            {
                "id": "de-15-panzer",
                "name": "15th Panzer Regiment",
                "role": "combat",
                "domain": "land",
                "attack": 6,
                "defense": 5,
                "morale": 5,
                "strength": 5,
                "max_strength": 5,
                "rof": 2,
                "tags": ["armor", "elite", "pursuit", "breakthrough"],
                "loss_priority": "normal",
            },
            {
                "id": "de-88s",
                "name": "88mm Artillery Detachment",
                "role": "support",
                "domain": "land",
                "attack": 5,
                "defense": 2,
                "morale": 4,
                "strength": 2,
                "max_strength": 2,
                "rof": 1,
                "tags": ["artillery"],
                "loss_priority": "last",
            },
            {
                "id": "de-stuka",
                "name": "Stuka Gruppe",
                "role": "combat",
                "domain": "air",
                "attack": 5,
                "defense": 3,
                "morale": 4,
                "strength": 2,
                "max_strength": 2,
                "rof": 1,
                "tags": ["air", "air_support", "dive_bomber", "land_attack"],
                "loss_priority": "normal",
            },
        ],
    },
    "defender": {
        "name": "Commonwealth",
        "leader": {"name": "O'Connor", "combat": 2, "morale": 2},
        "scenario_morale_bonus": 0,
        "boosters": [],
        "modifiers": [],
        "retreat_policy": {"mode": "when_bm_non_positive", "prevent_pursuit": True},
        "units": [
            {
                "id": "uk-matilda",
                "name": "Matilda Squadron",
                "role": "combat",
                "domain": "land",
                "attack": 4,
                "defense": 5,
                "morale": 5,
                "strength": 3,
                "max_strength": 3,
                "rof": 1,
                "tags": ["armor", "pursuit"],
                "loss_priority": "normal",
            },
            {
                "id": "uk-7-arm",
                "name": "7th Armoured Brigade",
                "role": "combat",
                "domain": "land",
                "attack": 4,
                "defense": 5,
                "morale": 4,
                "strength": 4,
                "max_strength": 4,
                "rof": 1,
                "tags": ["armor", "pursuit"],
                "loss_priority": "normal",
            },
            {
                "id": "uk-4-ind",
                "name": "4th Indian Brigade",
                "role": "combat",
                "domain": "land",
                "attack": 3,
                "defense": 4,
                "morale": 4,
                "strength": 5,
                "max_strength": 5,
                "rof": 1,
                "tags": ["infantry"],
                "loss_priority": "normal",
            },
            {
                "id": "uk-minefield",
                "name": "Minefield Screen",
                "role": "support",
                "domain": "land",
                "attack": 4,
                "defense": 4,
                "morale": 2,
                "strength": 2,
                "max_strength": 2,
                "rof": 1,
                "tags": ["mine", "minefield"],
                "loss_priority": "first",
            },
            {
                "id": "uk-25pdr",
                "name": "25-pdr Battery",
                "role": "support",
                "domain": "land",
                "attack": 4,
                "defense": 3,
                "morale": 4,
                "strength": 2,
                "max_strength": 2,
                "rof": 1,
                "tags": ["artillery"],
                "loss_priority": "last",
            },
        ],
    },
}


def example_battle() -> BattleInput:
    return BattleInput.model_validate(EXAMPLE_BATTLE)
